### ISSUE TITLE
Any plans for UDP support?

### ISSUE THREAD

**Issue by lonnietc** [nknorg/nconnect#43]
Hello,

I am now exploring all of the NKN stuff as I have just come across this wonderful work and in looking at the nconnect repository, it seems to allow you to establish a P2P VPN Mesh Network but only " TCP-based application". I am wondering if there are any plan to also support UDP as well as other transport layer protocols?

It also seems that UDP is significantly faster than TCP but is basically unreliable in terms of guaranteeing packer delivery which is why the new (-ish) QUIC protocol is now out so that you can have reliable UDP for faster communications, in general.

I am wondering if nconnect has plans to support UDP and perhaps QUIC, more specifically but this question could also be for the general nnet and NKN code base as well.

Thanks in advance

**Comment by yilunzhang** [comment]
Yes we are working on UDP support right now and a working version should be available very soon.

**Comment by lonnietc** [comment]
Thanks so very much for getting back to me so quicly on this. 

That is awesome and I will absolutely look forward to seeing it.

**Comment by yilunzhang** [comment]
Closing this issue as UDP support was implemented a while ago
